### Create and Update CDA maps for converting to FHIR with RESTClient and running matchbox (locally)
### Note: POST the maps in the following order, if you update one map you need to repost also the maps below

@host = https://test.ahdis.ch/r4
###@host = http://localhost:8080/r4


### 1. POST CdaToFhirTypes.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/CdaToFhirTypes.map


### 2. POST CdaToBundle.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/CdaToBundle.map


### 3. POST CdaChToBundle.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/CdaChToBundle.map




### 5a. Transform 1-ZuweisungZurRadiologischenDiagnostik.xml from CDA to FHIR
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/cda-fhir-maps/StructureMap/CdaChToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./input/cda-ch/1-ZuweisungZurRadiologischenDiagnostik.xml


### 5b. Transform CdaContainingOriginalRepresentationAsPdfA.xml from CDA to FHIR
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/cda-fhir-maps/StructureMap/CdaChToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./input/cda-ch/CdaContainingOriginalRepresentationAsPdfA.xml
