### Create and Update CDA maps for converting to FHIR with RESTClient and running matchbox (locally)
### Note: POST the maps in the following order, if you update one map you need to repost also the maps below

@host = https://test.ahdis.ch/matchbox/fhir
# @host = http://localhost:8080/matchboxv3/fhir

### 1. POST CdaToFhirTypes.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/CdaToFhirTypes.map


### 2. POST CdaToBundle.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/CdaToBundle.map


### 3. POST CdaChToBundle.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/CdaChToBundle.map


### 3b. POST CdaChEmedToBundle.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/CdaChEmedToBundle.map


### 4. POST CdaChEmedMedicationCardDocumentToBundle.map 
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/CdaChEmedMedicationCardDocumentToBundle.map

### 5. Transform Medication Card document (2-7-MedicationCard.xml) from CDA to FHIR
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/cda-fhir-maps/StructureMap/CdaChEmedMedicationCardDocumentToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./input/cda-ch-emed/2-7-MedicationCard.xml



###
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/cda-fhir-maps/StructureMap/CdaChEmedMedicationCardDocumentToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./input/generated-files/cda-ch-emed-2-7-MedicationCard.xml
