
@host = http://localhost:8080/r4

### FHIR to CDA

POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/FhirtoCdaTypes.map

###

POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/BundleToCda.map

###

POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/BundleToCdaCh.map


### BundleToCdaChEmedMedicationCardDocument


POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/BundleToCdaChEmedMedicationCardDocument.map



### Transform 2-7-MedicationCard.fhir.xml

POST {{host}}/StructureMap/$transform?source=http://ahdis.ch/ig/cda-fhir-maps/StructureMap/BundleToCdaChEmedMedicationCardDocument
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0


< ./resources/examples/2-7-MedicationCard.fhir.xml
