### Create and Update FHIR maps for converting to CDA with RESTClient and running matchbox (locally)
### Note: POST the maps in the following order, if you update one map you need to repost also the maps below

@host = https://test.ahdis.ch/r4
### @host = http://localhost:8080/r4


### 1. POST FhirtoCdaTypes.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/FhirtoCdaTypes.map


### 2. POST BundleToCda.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/BundleToCda.map


### 3. POST BundleToCdaCh.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/BundleToCdaCh.map


### 4. POST BundleToCdaChEmedMedicationDispenseDocument.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./input/maps/BundleToCdaChEmedMedicationDispenseDocument.map


### 5a. Transform Medication Dispense document (1-2-MedicationDispense.xml) from FHIR to CDA
POST {{host}}/StructureMap/$transform?source=http://ahdis.ch/ig/cda-fhir-maps/StructureMap/BundleToCdaChEmedMedicationDispenseDocument
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./input/ch-emed/1-2-MedicationDispense.xml


### 5b. Transform Medication Dispense document (2-4-MedicationDispense.xml) from FHIR to CDA
POST {{host}}/StructureMap/$transform?source=http://ahdis.ch/ig/cda-fhir-maps/StructureMap/BundleToCdaChEmedMedicationDispenseDocument
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./input/ch-emed/2-4-MedicationDispense.xml
